#----------------------------------------------------------------------
# This file was generated by C:\Python36\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

# Use "img2py img.png img.py" to generate this
# Be careful, xnview will remove transparency from PNG <8bit images


justify = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAMCAIAAADkharWAAAACXBIWXMAAAsSAAALEgHS3X78'
    b'AAAAyUlEQVQokZVQQY6EMAyr3Wa7g4SQkPgE4l38kRMfgmOhM5RmDpVW7FyWzclRHNsJ6ro2'
    b't0tEEGO8vwDATdNUoDinqjlnAB8kY0xKqWAMwwDgOI5lWbz3XyLpPEnmnAsjpaSqbduSdM5B'
    b'Va96IYRnjABpCWOer1fXdb8Mx3EsSiJynmcIIed8VWma5ieStdZ578tAVQHs+x5jtOT347Ft'
    b'W5mSLMBa+xnp70f1fX/tSV4NjTHl+lLOOczzfF+eJNZ1/V+kqqrus0XkDfHUWAm4WjS6AAAA'
    b'AElFTkSuQmCC')



center_align = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAA+IAAAPiAEWyKWG'
    b'AAAA9klEQVQ4jaVTsW2EQBCc5ZD2ElrABCfRgDswGXWQkFALCZILIcMN8BVYIuBrILkVutsP'
    b'rI/8tpBu09XMjmZmSVWRMvntdntPIaCyLHcAUFUKIZgrIGNMICIFADrPMwcAIlJjTLhCEEIw'
    b'qkoAQDFGIiLd9/1tnueWmeW5/CWXSEWE27adq6q6qyrlIsLWWr9tm5umqS+K4ogxZq8IsiyL'
    b'x3EUdV1/V1V1FxGm1BSo67pP4MfEvy6/UvI08RLgXwXJRfLeW2utX5blYxiG8YqJ4zgOTdN8'
    b'ee9tzswCAM65re/76UqMzrkNAJhZ0ouUXOV1XdOeKTWFB0ftljHMZ7vTAAAAAElFTkSuQmCC')


left_align = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAEJJ"
    b"REFUOI1jZGRiZqAEMFGkm4GBgYWBgYHBx9vrPzmat2zdxshIqRdIcsGWrdsY0cXo6wJsLhoN"
    b"g2ERBhRnJooNAACQdhhQZbXeGAAAAABJRU5ErkJggg==")

right_align = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAADxJ"
    b"REFUOI1jZGRiZqAEMFGkm4GBgYWBgYHBx9vrPzmat2zdxshIqRdYsAkS6yLquWA0DEZ8GFCc"
    b"mSg2AADQZxhQFG0xxgAAAABJRU5ErkJggg==")

bold = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAEtJ"
    b"REFUOI3NUkEKACAMyq3//7jWNQwWY0HzKNOJCIi2DCSlfmHQmbA5zBNAFG4CPoAodo4fFOyA"
    b"wZGvHTDqdwCecnQHh0EU/ztIGyy1dBRJuH/9MwAAAABJRU5ErkJggg==")

center_align = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAEJJ"
    b"REFUOI1jZGRiZqAEMFGkm4GBgYWBgYHBx9vrPzmat2zdxshIqRdYkDnEumTL1m2MMDZ1XDAa"
    b"BiM+DCjOTBQbAAAwdhhQDziCqAAAAABJRU5ErkJggg==")


italic = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGdJ"
    b"REFUOI3Vk1EOgDAIQwt4/2P0lopfS6YOgsEfl+xntK8kMBE1dI623F8Atqzox+73N1GTcgez"
    b"mOTDPEThJekAHIBHmhQwzCTfAyrpKaCSHgKq6SGgmi5qkHmVV3Nfzf5S+/9faANOrocplI0e"
    b"xSoAAAAASUVORK5CYII=")

underline = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAFdJ"
    b"REFUOI1jZGRiZqAEMFGkmxoGsKAL/P/39z8yn5GJmRGbGE4XIEvC2NjEcBpAKhg1gIABS5cs"
    b"/o9MYwOMuJIyetwzMGBGIV4DiAUEUyI2gJKwBjw3AgDOdhYrghF5ggAAAABJRU5ErkJggg==")
